// <auto-generated />
namespace LearingCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Initialtableadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialtableadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202512031250119_Initial-table-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
